Let us define ANN (Artificial Neural Networks) to classify Maternal risk

In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [6]:
#Load the Dataset
df=pd.read_csv("Maternal Health Risk Data Set.csv")

In [7]:
print(df.head())

   Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  RiskLevel
0   25         130           80  15.0      98.0         86  high risk
1   35         140           90  13.0      98.0         70  high risk
2   29          90           70   8.0     100.0         80  high risk
3   30         140           85   7.0      98.0         70  high risk
4   35         120           60   6.1      98.0         76   low risk


In [8]:
df.head()

,Age,SystolicBP,DiastolicBP,BS,BodyTemp,HeartRate,RiskLevel
0,25,130,80,15.0,98.0,86,high risk
1,35,140,90,13.0,98.0,70,high risk
2,29,90,70,8.0,100.0,80,high risk
3,30,140,85,7.0,98.0,70,high risk
4,35,120,60,6.1,98.0,76,low risk


In [9]:
#Let us check null values
df.isnull().sum()

Age            0
SystolicBP     0
DiastolicBP    0
BS             0
BodyTemp       0
HeartRate      0
RiskLevel      0
dtype: int64

In [10]:
#Let us split features and target
X=df.drop("RiskLevel", axis=1)   #Inserting all features to X by dropping RiskLevel column
y=df['RiskLevel']                #Inserting RiskLevel column feature to y axis

In [11]:
#Let us encode the target (converting string to interger of given data set of the target (risk, mid risk, high risk into 0,1,2))
encoder=LabelEncoder()
y=encoder.fit_transform(y)

In [12]:
y

array([0, 0, 0, ..., 0, 0, 2], shape=(1014,))

In [13]:
#Let us split train and test data

Xtrain, Xtest, ytrain, ytest=train_test_split(X,y,test_size=0.2, random_state=43)

In [14]:
#Features Scaling

scaler=StandardScaler()
Xtrain=scaler.fit_transform(Xtrain)
Xtest=scaler.transform(Xtest)

In [15]:
Xtrain[0]

array([ 0.84609405, -1.28420713, -1.22513551, -0.38520191, -0.48036722,
        0.20718281])

In [16]:
Xtest[0]

array([-0.9913692 , -1.28420713, -0.86277778, -0.38520191,  3.215817  ,
       -0.89502369])

In [17]:
#Let us Build Model
model=Sequential()
model.add(Dense(16, activation="relu", input_shape=(6,)))           #6 features(6 columns)
model.add(Dense(8, activation="relu"))
model.add(Dense(3, activation="softmax"))       #Since it is multiclass output we using softmax activation type. For Binary class we use Sigmoid

f:\Python class\.venv\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [18]:
#Let us set compile option

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"])

In [19]:
history=model.fit(
    Xtrain,
    ytrain,
    epochs=100,
    batch_size=16,
    validation_split=0.2,
    verbose=1
)

Epoch 1/100
41/41 ━━━━━━━━━━━━━━━━━━━━ 8s 20ms/step - accuracy: 0.4290 - loss: 1.1114 - val_accuracy: 0.4601 - val_loss: 1.1017
Epoch 2/100
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5278 - loss: 1.0379 - val_accuracy: 0.5460 - val_loss: 1.0477
Epoch 3/100
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5756 - loss: 0.9793 - val_accuracy: 0.5644 - val_loss: 1.0000
Epoch 4/100
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6219 - loss: 0.9227 - val_accuracy: 0.6196 - val_loss: 0.9467
Epoch 5/100
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6343 - loss: 0.8668 - val_accuracy: 0.6258 - val_loss: 0.9010
Epoch 6/100
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6435 - loss: 0.8238 - val_accuracy: 0.6319 - val_loss: 0.8668
Epoch 7/100
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6512 - loss: 0.7921 - val_accuracy: 0.6258 - val_loss: 0.8415
Epoch 8/100
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6605 - loss: 0.7668 - val_accuracy: 0.6380 - 

In [20]:

print("Training accuracy: ", history.history['accuracy'][-1]*100)
print("Validation accuracy: ", history.history['val_accuracy'][-1]*100)


Training accuracy:  74.0740716457367
Validation accuracy:  65.0306761264801


In [21]:
test_data=np.array([[25,13,80,15,98,86]])
test_data=scaler.transform(test_data)
pred=model.predict(test_data)
print(f"Result of prediction ={pred[0]}")

index=np.argmax(pred)
print(f"Predicted index is: {index}")

#Test data and validaion data is different
#total data=1000, 800=train data, 200=test data. in 800 train data 640 is trained data and 160 is validation data

f:\Python class\.venv\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 198ms/step
Result of prediction =[0.24583954 0.462434   0.29172653]
Predicted index is: 1


In [22]:
ypred=model.predict(Xtest)
# ypred=np.argmax(ypred,axis=1)

ypred           #output will be in probability. 


7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step


array([[7.24282622e-01, 1.43214092e-01, 1.32503316e-01],
       [5.15301130e-04, 9.32084441e-01, 6.74003065e-02],
       [1.29821403e-02, 5.06793439e-01, 4.80224401e-01],
       [8.67038220e-03, 5.08063734e-01, 4.83265936e-01],
       [9.24467921e-01, 1.02668745e-03, 7.45054558e-02],
       [6.98784352e-05, 8.88723731e-01, 1.11206435e-01],
       [6.31900504e-03, 9.06500816e-01, 8.71802047e-02],
       [1.51949292e-02, 6.60078347e-01, 3.24726790e-01],
       [3.36084195e-04, 8.03856850e-01, 1.95807040e-01],
       [5.91194862e-03, 4.01932895e-01, 5.92155218e-01],
       [3.50058079e-04, 3.93962771e-01, 6.05687201e-01],
       [1.31993966e-05, 4.59963202e-01, 5.40023565e-01],
       [2.86424020e-03, 4.82526630e-01, 5.14609098e-01],
       [9.53986347e-01, 4.81189723e-04, 4.55325060e-02],
       [9.84399080e-01, 2.87416715e-05, 1.55721214e-02],
       [3.50058079e-04, 3.93962771e-01, 6.05687201e-01],
       [9.83942449e-01, 3.09422285e-05, 1.60266366e-02],
       [4.21654386e-03, 8.12069

In [23]:
ypred=np.argmax(ypred,axis=1)       #Converting the ypred data from pobablity to decision

ypred

array([0, 1, 1, 1, 0, 1, 1, 1, 1, 2, 2, 2, 2, 0, 0, 2, 0, 1, 0, 0, 2, 0,
       1, 2, 2, 0, 0, 2, 1, 2, 0, 0, 0, 1, 1, 2, 1, 1, 2, 2, 0, 2, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 2, 0, 1, 2, 2, 0, 1, 1, 1, 2, 1, 1, 2,
       1, 1, 1, 0, 1, 2, 0, 0, 2, 1, 0, 0, 2, 0, 0, 2, 0, 2, 2, 2, 2, 1,
       1, 1, 2, 0, 1, 1, 1, 2, 0, 2, 0, 2, 2, 0, 0, 0, 2, 1, 0, 1, 2, 1,
       1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 2, 1, 2,
       2, 2, 1, 1, 1, 2, 0, 1, 0, 1, 1, 2, 0, 1, 1, 2, 1, 1, 1, 2, 1, 1,
       1, 0, 2, 2, 0, 2, 1, 0, 1, 2, 1, 1, 0, 1, 0, 1, 0, 1, 2, 1, 2, 2,
       1, 2, 0, 1, 1, 1, 0, 2, 1, 1, 2, 0, 2, 2, 0, 2, 2, 1, 0, 2, 1, 2,
       0, 1, 0, 2, 1])

In [24]:
print(len(ypred), len(ytest))

203 203


In [25]:
ytest

array([1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 2, 2, 2, 0, 0, 2, 0, 2, 0, 0, 2, 0,
       2, 1, 0, 2, 0, 2, 1, 2, 0, 0, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1,
       0, 1, 1, 2, 1, 0, 1, 0, 2, 1, 0, 2, 2, 2, 1, 1, 1, 1, 2, 2, 1, 2,
       0, 0, 2, 0, 2, 1, 0, 0, 1, 1, 2, 0, 1, 0, 0, 0, 0, 1, 2, 2, 0, 2,
       1, 1, 2, 2, 1, 1, 0, 2, 0, 1, 0, 0, 1, 2, 0, 2, 2, 1, 0, 1, 0, 1,
       1, 2, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 0, 0, 1, 0, 2, 0, 0, 2, 1, 2,
       2, 2, 1, 1, 2, 1, 0, 1, 0, 2, 2, 1, 2, 1, 1, 1, 1, 0, 1, 2, 1, 1,
       1, 2, 1, 2, 2, 0, 1, 0, 2, 2, 1, 2, 0, 1, 0, 2, 0, 2, 2, 1, 2, 1,
       2, 0, 0, 1, 1, 2, 2, 2, 1, 1, 2, 0, 1, 1, 0, 2, 1, 1, 2, 2, 1, 1,
       0, 1, 2, 2, 1])

In [26]:
score=accuracy_score(ytest,ypred)
print(f"Accuracy score of score : {score*100}")

Accuracy score of score : 66.00985221674877


In [27]:
cm=confusion_matrix(ypred, ytest)
print(cm)

[[39  4 11]
 [ 5 61 22]
 [ 7 20 34]]


In [28]:
print(ypred.shape)
print(ypred[:5])

(203,)
[0 1 1 1 0]


In [29]:
encoder.classes_            #output= 0=high risk, 1=Low risk, 2= Mid risk

array(['high risk', 'low risk', 'mid risk'], dtype=object)

In [30]:
#Let us save the model
model.save("maternal_ann.keras")

In [31]:
import joblib
joblib.dump(scaler,"scaler.pkl")

['scaler.pkl']

In [ ]:
joblib.dump(encoder, "label_encoder.pkl")

['label_encoder.pkl']